### ISSUE TITLE
Organize the PSR-2 coding style

### ISSUE THREAD

**Issue by peter279k** [nathan-fiscaletti/ipstackgeo-php#13]
How about organize the PSR-2 coding style for this repository?
Also, using the camel-case to declare the methods.

**Comment by nathan-fiscaletti** [comment]
This repository uses  a slightly altered version of the PSR-2 coding standard. It uses the same standard as Laravel. So this is already done.

**Comment by peter279k** [comment]
@nathan-fiscaletti, thank you for your explanation.
I know that, but I cannot see any `.styleci.yml` to define the coding style.
Perhaps we can define the coding style to integrate the StyleCI service :).

**Comment by nathan-fiscaletti** [comment]
StyleCI is already integrated, and the style definitions are configured in StyleCI. There is a hook on this repository that will automatically validate the coding style before allowing a PR to be processed.
